name: Backend Coverage
on:
  pull_request:
    paths:
      - "backend/**"

permissions:
  contents: read
  pull-requests: write
jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Run tests with coverage
      working-directory: backend/src/altinn-support-dashboard.backend
      run: dotnet test --collect:"XPlat Code Coverage"

    - name: Generate Coverage Summary
      uses: irongut/CodeCoverageSummary@f13848964841ca2f7a63343b287493e17dc645de
      with:
        format: markdown
        files: "backend/altinn-support-dashboard.backend.Tests/TestResults/**/coverage.cobertura.xml"
        output: "both"
        fail_below_min: false
        badge: true

    - name: Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@5060d4700a91de252c87eeddd2da026382d9298a
      with:
        header: "ðŸŸª Backend Code Coverage"
        recreate: true
        path: "code-coverage-results.md"
