     
  backend:
    name: Backend C# Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # or your version

      - name: Restore dependencies
        run: dotnet restore ./backend/src/altinn-support-dashboard.backend

      - name: Build backend (warnings as errors)
        run: dotnet build ./backend/src/altinn-support-dashboard.backend --no-restore /warnaserror

        # Test pluss coverage
      - name: Run tests with coverage
        run: dotnet test --collect:"XPlat Code Coverage" || true

      - name: Generate Coverage Summary
        uses: irongut/CodeCoverageSummary@f13848964841ca2f7a63343b287493e17dc645de
        with:
          format: markdown
          filename: "backend/test/altinn-support-dashboard.backend.Tests/TestResults/**/coverage.cobertura.xml"
          output: "both"
          fail_below_min: false
          badge: true

      - name: Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@5060d4700a91de252c87eeddd2da026382d9298a
        with:
          header: "ðŸŸª Backend Code Coverage"
          recreate: true
          path: "code-coverage-results.md"
