name: Backend CI checks
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main

jobs:

  backend:
    name: Backend C# Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup .NET
        uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5
        with:
          dotnet-version: '10.x' # or your version

      - name: Restore dependencies
        run: dotnet restore ./backend/src/altinn-support-dashboard.backend

      - name: Build backend (warnings as errors)
        run: dotnet build ./backend/src/altinn-support-dashboard.backend --no-restore /warnaserror

        # Test pluss coverage
      - name: Run tests with coverage
        run: dotnet test --settings coverlet.runsettings
        working-directory: backend/test/altinn-support-dashboard.backend.Tests

      - name: Generate Coverage Summary
        uses: irongut/CodeCoverageSummary@f13848964841ca2f7a63343b287493e17dc645de
        with:
          format: markdown
          filename: "backend/test/altinn-support-dashboard.backend.Tests/TestResults/**/coverage.cobertura.xml"
          output: "both"
          fail_below_min: false
          badge: true
          packagename: "frontend"

      - name: Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@5060d4700a91de252c87eeddd2da026382d9298a
        with:
          header: "Backend Code Coverage"
          recreate: true
          path: "code-coverage-results.md"
