name: Frontend Coverage
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    paths:
      - "frontend/altinn-support-dashboard.client/**"

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "npm"
        cache-dependency-path: frontend/altinn-support-dashboard.client/package-lock.json

    - name: Install dependencies
      working-directory: frontend/altinn-support-dashboard.client
      run: npm ci

    - name: Run tests with coverage
      working-directory: frontend/altinn-support-dashboard.client
      run: npm test -- --coverage

    - name: Generate Coverage Summary
      uses: irongut/CodeCoverageSummary@f13848964841ca2f7a63343b287493e17dc645de
      with:
        format: markdown
        files: "frontend/altinn-support-dashboard.client/coverage/lcov.info"
        output: "both"
        fail_below_min: false
        badge: true                 
        badge_lower: 50           
        badge_upper: 75 

    - name: Post PR Comment
      uses: marocchino/sticky-pull-request-comment@5060d4700a91de252c87eeddd2da026382d9298a
      with:
        header: "ðŸŸ¦ Frontend Code Coverage"
        recreate: true
        path: "code-coverage-results.md"
